/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as OrgsNewRouteImport } from './routes/orgs/new'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as OrgSlugAuthenticatedRouteRouteImport } from './routes/$orgSlug/_authenticated/route'
import { Route as OrgSlugAuthenticatedIndexRouteImport } from './routes/$orgSlug/_authenticated/index'
import { Route as OrgSlugAuthenticatedSettingsRouteRouteImport } from './routes/$orgSlug/_authenticated/settings/route'
import { Route as OrgSlugAuthenticatedUsersIndexRouteImport } from './routes/$orgSlug/_authenticated/users/index'
import { Route as OrgSlugAuthenticatedSettingsIndexRouteImport } from './routes/$orgSlug/_authenticated/settings/index'
import { Route as OrgSlugAuthenticatedSettingsNotificationsRouteImport } from './routes/$orgSlug/_authenticated/settings/notifications'
import { Route as OrgSlugAuthenticatedSettingsDisplayRouteImport } from './routes/$orgSlug/_authenticated/settings/display'
import { Route as OrgSlugAuthenticatedSettingsAppearanceRouteImport } from './routes/$orgSlug/_authenticated/settings/appearance'
import { Route as OrgSlugAuthenticatedSettingsAccountRouteImport } from './routes/$orgSlug/_authenticated/settings/account'

const OrgSlugRouteImport = createFileRoute('/$orgSlug')()

const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAuthenticatedRouteRoute =
  OrgSlugAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugAuthenticatedIndexRoute =
  OrgSlugAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugAuthenticatedRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsRouteRoute =
  OrgSlugAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgSlugAuthenticatedRouteRoute,
  } as any)
const OrgSlugAuthenticatedUsersIndexRoute =
  OrgSlugAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => OrgSlugAuthenticatedRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsIndexRoute =
  OrgSlugAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugAuthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsNotificationsRoute =
  OrgSlugAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => OrgSlugAuthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsDisplayRoute =
  OrgSlugAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => OrgSlugAuthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsAppearanceRoute =
  OrgSlugAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => OrgSlugAuthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugAuthenticatedSettingsAccountRoute =
  OrgSlugAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => OrgSlugAuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/orgs/new': typeof OrgsNewRoute
  '/orgs': typeof OrgsIndexRoute
  '/$orgSlug/settings': typeof OrgSlugAuthenticatedSettingsRouteRouteWithChildren
  '/$orgSlug/': typeof OrgSlugAuthenticatedIndexRoute
  '/$orgSlug/settings/account': typeof OrgSlugAuthenticatedSettingsAccountRoute
  '/$orgSlug/settings/appearance': typeof OrgSlugAuthenticatedSettingsAppearanceRoute
  '/$orgSlug/settings/display': typeof OrgSlugAuthenticatedSettingsDisplayRoute
  '/$orgSlug/settings/notifications': typeof OrgSlugAuthenticatedSettingsNotificationsRoute
  '/$orgSlug/settings/': typeof OrgSlugAuthenticatedSettingsIndexRoute
  '/$orgSlug/users': typeof OrgSlugAuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugAuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/orgs/new': typeof OrgsNewRoute
  '/orgs': typeof OrgsIndexRoute
  '/$orgSlug/settings/account': typeof OrgSlugAuthenticatedSettingsAccountRoute
  '/$orgSlug/settings/appearance': typeof OrgSlugAuthenticatedSettingsAppearanceRoute
  '/$orgSlug/settings/display': typeof OrgSlugAuthenticatedSettingsDisplayRoute
  '/$orgSlug/settings/notifications': typeof OrgSlugAuthenticatedSettingsNotificationsRoute
  '/$orgSlug/settings': typeof OrgSlugAuthenticatedSettingsIndexRoute
  '/$orgSlug/users': typeof OrgSlugAuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/$orgSlug/_authenticated': typeof OrgSlugAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/orgs/new': typeof OrgsNewRoute
  '/orgs/': typeof OrgsIndexRoute
  '/$orgSlug/_authenticated/settings': typeof OrgSlugAuthenticatedSettingsRouteRouteWithChildren
  '/$orgSlug/_authenticated/': typeof OrgSlugAuthenticatedIndexRoute
  '/$orgSlug/_authenticated/settings/account': typeof OrgSlugAuthenticatedSettingsAccountRoute
  '/$orgSlug/_authenticated/settings/appearance': typeof OrgSlugAuthenticatedSettingsAppearanceRoute
  '/$orgSlug/_authenticated/settings/display': typeof OrgSlugAuthenticatedSettingsDisplayRoute
  '/$orgSlug/_authenticated/settings/notifications': typeof OrgSlugAuthenticatedSettingsNotificationsRoute
  '/$orgSlug/_authenticated/settings/': typeof OrgSlugAuthenticatedSettingsIndexRoute
  '/$orgSlug/_authenticated/users/': typeof OrgSlugAuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/orgs/new'
    | '/orgs'
    | '/$orgSlug/settings'
    | '/$orgSlug/'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/settings/appearance'
    | '/$orgSlug/settings/display'
    | '/$orgSlug/settings/notifications'
    | '/$orgSlug/settings/'
    | '/$orgSlug/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/orgs/new'
    | '/orgs'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/settings/appearance'
    | '/$orgSlug/settings/display'
    | '/$orgSlug/settings/notifications'
    | '/$orgSlug/settings'
    | '/$orgSlug/users'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/$orgSlug/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/orgs/new'
    | '/orgs/'
    | '/$orgSlug/_authenticated/settings'
    | '/$orgSlug/_authenticated/'
    | '/$orgSlug/_authenticated/settings/account'
    | '/$orgSlug/_authenticated/settings/appearance'
    | '/$orgSlug/_authenticated/settings/display'
    | '/$orgSlug/_authenticated/settings/notifications'
    | '/$orgSlug/_authenticated/settings/'
    | '/$orgSlug/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  OrgsNewRoute: typeof OrgsNewRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/_authenticated': {
      id: '/$orgSlug/_authenticated'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugAuthenticatedRouteRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/_authenticated/': {
      id: '/$orgSlug/_authenticated/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugAuthenticatedIndexRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRouteRoute
    }
    '/$orgSlug/_authenticated/settings': {
      id: '/$orgSlug/_authenticated/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRouteRoute
    }
    '/$orgSlug/_authenticated/users/': {
      id: '/$orgSlug/_authenticated/users/'
      path: '/users'
      fullPath: '/$orgSlug/users'
      preLoaderRoute: typeof OrgSlugAuthenticatedUsersIndexRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRouteRoute
    }
    '/$orgSlug/_authenticated/settings/': {
      id: '/$orgSlug/_authenticated/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof OrgSlugAuthenticatedSettingsRouteRoute
    }
    '/$orgSlug/_authenticated/settings/notifications': {
      id: '/$orgSlug/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/$orgSlug/settings/notifications'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof OrgSlugAuthenticatedSettingsRouteRoute
    }
    '/$orgSlug/_authenticated/settings/display': {
      id: '/$orgSlug/_authenticated/settings/display'
      path: '/display'
      fullPath: '/$orgSlug/settings/display'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof OrgSlugAuthenticatedSettingsRouteRoute
    }
    '/$orgSlug/_authenticated/settings/appearance': {
      id: '/$orgSlug/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/$orgSlug/settings/appearance'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof OrgSlugAuthenticatedSettingsRouteRoute
    }
    '/$orgSlug/_authenticated/settings/account': {
      id: '/$orgSlug/_authenticated/settings/account'
      path: '/account'
      fullPath: '/$orgSlug/settings/account'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof OrgSlugAuthenticatedSettingsRouteRoute
    }
  }
}

interface OrgSlugAuthenticatedSettingsRouteRouteChildren {
  OrgSlugAuthenticatedSettingsAccountRoute: typeof OrgSlugAuthenticatedSettingsAccountRoute
  OrgSlugAuthenticatedSettingsAppearanceRoute: typeof OrgSlugAuthenticatedSettingsAppearanceRoute
  OrgSlugAuthenticatedSettingsDisplayRoute: typeof OrgSlugAuthenticatedSettingsDisplayRoute
  OrgSlugAuthenticatedSettingsNotificationsRoute: typeof OrgSlugAuthenticatedSettingsNotificationsRoute
  OrgSlugAuthenticatedSettingsIndexRoute: typeof OrgSlugAuthenticatedSettingsIndexRoute
}

const OrgSlugAuthenticatedSettingsRouteRouteChildren: OrgSlugAuthenticatedSettingsRouteRouteChildren =
  {
    OrgSlugAuthenticatedSettingsAccountRoute:
      OrgSlugAuthenticatedSettingsAccountRoute,
    OrgSlugAuthenticatedSettingsAppearanceRoute:
      OrgSlugAuthenticatedSettingsAppearanceRoute,
    OrgSlugAuthenticatedSettingsDisplayRoute:
      OrgSlugAuthenticatedSettingsDisplayRoute,
    OrgSlugAuthenticatedSettingsNotificationsRoute:
      OrgSlugAuthenticatedSettingsNotificationsRoute,
    OrgSlugAuthenticatedSettingsIndexRoute:
      OrgSlugAuthenticatedSettingsIndexRoute,
  }

const OrgSlugAuthenticatedSettingsRouteRouteWithChildren =
  OrgSlugAuthenticatedSettingsRouteRoute._addFileChildren(
    OrgSlugAuthenticatedSettingsRouteRouteChildren,
  )

interface OrgSlugAuthenticatedRouteRouteChildren {
  OrgSlugAuthenticatedSettingsRouteRoute: typeof OrgSlugAuthenticatedSettingsRouteRouteWithChildren
  OrgSlugAuthenticatedIndexRoute: typeof OrgSlugAuthenticatedIndexRoute
  OrgSlugAuthenticatedUsersIndexRoute: typeof OrgSlugAuthenticatedUsersIndexRoute
}

const OrgSlugAuthenticatedRouteRouteChildren: OrgSlugAuthenticatedRouteRouteChildren =
  {
    OrgSlugAuthenticatedSettingsRouteRoute:
      OrgSlugAuthenticatedSettingsRouteRouteWithChildren,
    OrgSlugAuthenticatedIndexRoute: OrgSlugAuthenticatedIndexRoute,
    OrgSlugAuthenticatedUsersIndexRoute: OrgSlugAuthenticatedUsersIndexRoute,
  }

const OrgSlugAuthenticatedRouteRouteWithChildren =
  OrgSlugAuthenticatedRouteRoute._addFileChildren(
    OrgSlugAuthenticatedRouteRouteChildren,
  )

interface OrgSlugRouteChildren {
  OrgSlugAuthenticatedRouteRoute: typeof OrgSlugAuthenticatedRouteRouteWithChildren
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugAuthenticatedRouteRoute: OrgSlugAuthenticatedRouteRouteWithChildren,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  OrgsNewRoute: OrgsNewRoute,
  OrgsIndexRoute: OrgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
